// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/linclin",
        "contact": {
            "name": "LC",
            "url": "https://github.com/linclin",
            "email": "13579443@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/apilog/get/{requestid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]日志"
                ],
                "summary": "[系统内部]根据ID获取接口日志",
                "operationId": "GetApiLogById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RequestId",
                        "name": "requestid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/apilog/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]日志"
                ],
                "summary": "[系统内部]获取服务接口日志",
                "operationId": "GetApiLog",
                "parameters": [
                    {
                        "description": "RQL查询json",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Req"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/base/auth": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]Token"
                ],
                "summary": "[系统内部]获取token",
                "operationId": "auth",
                "parameters": [
                    {
                        "description": "token请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Token"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/cronjoblog/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]日志"
                ],
                "summary": "[系统内部]获取定时任务日志",
                "operationId": "GetCronjobLog",
                "parameters": [
                    {
                        "description": "RQL查询json",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Req"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/reqapilog/get/{requestid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]日志"
                ],
                "summary": "[系统内部]根据ID获取请求接口日志",
                "operationId": "GetReqApiLogById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RequestId",
                        "name": "requestid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/reqapilog/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]日志"
                ],
                "summary": "[系统内部]获取请求接口日志",
                "operationId": "GetReqApiLog",
                "parameters": [
                    {
                        "description": "RQL查询json",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Req"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]创建角色",
                "operationId": "3 CreateRole",
                "parameters": [
                    {
                        "description": "角色",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sys.SysRole"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]删除角色",
                "operationId": "DeleteRoleById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/get/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]根据ID获取角色",
                "operationId": "2 GetRoleById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]获取角色列表",
                "operationId": "1 GetRoles",
                "parameters": [
                    {
                        "description": "RQL查询json",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Req"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/perm/create/{id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]创建角色权限",
                "operationId": "CreateRolePerm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色权限",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sys.RbacRolePerm"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/perm/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]删除角色权限",
                "operationId": "DeleteRolePermById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色权限",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sys.RbacRolePerm"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/perm/get/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]获取角色所有权限",
                "operationId": "GetRolePermById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/update/{id}": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]更新角色",
                "operationId": "4 UpdateRoleById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sys.SysRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/users/create/{id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]创建角色用户",
                "operationId": "CreateRoleUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用户",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/users/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]删除角色用户",
                "operationId": "DeleteRoleUserById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用户",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/role/users/get/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]角色"
                ],
                "summary": "[系统内部]获取角色所有用户",
                "operationId": "GetRoleUsersById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/router/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]路由"
                ],
                "summary": "[系统内部]获取系统路由",
                "operationId": "GetRouters",
                "parameters": [
                    {
                        "description": "RQL查询json",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Req"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/system/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]系统"
                ],
                "summary": "[系统内部]创建系统",
                "operationId": "CreateSystem",
                "parameters": [
                    {
                        "description": "系统",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sys.SysSystem"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/system/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]系统"
                ],
                "summary": "[系统内部]删除系统",
                "operationId": "DeleteSystemById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "系统ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/system/get/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]系统"
                ],
                "summary": "[系统内部]根据ID获取系统",
                "operationId": "GetSystemById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "系统ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/system/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]系统"
                ],
                "summary": "[系统内部]获取系统列表",
                "operationId": "GetSystems",
                "parameters": [
                    {
                        "description": "RQL查询json",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Req"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/system/perm/create/{id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]系统"
                ],
                "summary": "[系统内部]创建系统权限",
                "operationId": "CreateSystemPerm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "系统ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "系统权限",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sys.RbacRolePerm"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/system/perm/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]系统"
                ],
                "summary": "[系统内部]删除系统权限",
                "operationId": "DeleteSystemPermById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "系统ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "系统权限",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sys.RbacRolePerm"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/system/perm/get/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]系统"
                ],
                "summary": "[系统内部]获取系统所有权限",
                "operationId": "GetSystemPermById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "系统ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/api/v1/system/update/{id}": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]系统"
                ],
                "summary": "[系统内部]更新系统",
                "operationId": "UpdateSystemById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "系统ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "系统",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sys.SysSystem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        },
        "/heatch_check": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "[系统内部]路由"
                ],
                "summary": "[系统内部]健康检查接口",
                "operationId": "HeathCheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Resp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm_io_gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "models.Req": {
            "type": "object",
            "properties": {
                "filter": {
                    "description": "Filter is the query object for building the value for the ` + "`" + `WHERE` + "`" + ` clause.\nThe full documentation of the supported operators is writtern in the README.\nAn example for filter object:\n\n\tparams, err := p.Parse([]byte(` + "`" + `{\n\t\t\"filter\": {\n\t\t\t\"account\": { \"$like\": \"%github%\" },\n\t\t\t\"$or\": [\n\t\t\t\t{ \"city\": \"TLV\" },\n\t\t\t\t{ \"city\": \"NYC\" }\n\t\t\t]\n\t\t}\n\t}` + "`" + `))",
                    "type": "object",
                    "additionalProperties": true
                },
                "limit": {
                    "description": "Limit must be \u003e 0 and \u003c= to ` + "`" + `LimitMaxValue` + "`" + `.",
                    "type": "integer"
                },
                "offset": {
                    "description": "Offset must be \u003e= 0.",
                    "type": "integer"
                },
                "select": {
                    "description": "Select contains the list of expressions define the value for the ` + "`" + `SELECT` + "`" + ` clause.\nFor example:\n\n\tparams, err := p.Parse([]byte(` + "`" + `{\n\t\t\"select\": [\"name\", \"age\"]\n\t}` + "`" + `))",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sort": {
                    "description": "Sort contains list of expressions define the value for the ` + "`" + `ORDER BY` + "`" + ` clause.\nIn order to return the rows in descending order you can prefix your field with ` + "`" + `-` + "`" + `.\nFor example:\n\n\tparams, err := p.Parse([]byte(` + "`" + `{\n\t\t\"sort\": [\"name\", \"-age\", \"+redundant\"]\n\t}` + "`" + `))",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ReqToken": {
            "type": "object",
            "required": [
                "AppId",
                "AppSecret"
            ],
            "properties": {
                "AppId": {
                    "description": "AppId",
                    "type": "string"
                },
                "AppSecret": {
                    "description": "AppSecret",
                    "type": "string"
                }
            }
        },
        "models.Resp": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据内容"
                },
                "msg": {
                    "description": "消息提示",
                    "type": "string"
                },
                "request_id": {
                    "description": "请求ID",
                    "type": "string"
                }
            }
        },
        "models.Token": {
            "type": "object",
            "properties": {
                "expires": {
                    "description": "过期时间",
                    "type": "string"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                }
            }
        },
        "sys.RbacRolePerm": {
            "type": "object",
            "required": [
                "absolutePath",
                "httpMethod"
            ],
            "properties": {
                "absolutePath": {
                    "description": "路由地址",
                    "type": "string"
                },
                "httpMethod": {
                    "description": "HTTP方法",
                    "type": "string"
                }
            }
        },
        "sys.SysRole": {
            "type": "object",
            "required": [
                "Name"
            ],
            "properties": {
                "Desc": {
                    "description": "角色说明",
                    "type": "string"
                },
                "Keyword": {
                    "description": "角色关键词",
                    "type": "string"
                },
                "Name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "Operator": {
                    "type": "string"
                },
                "Status": {
                    "description": "角色状态(正常/禁用, 默认正常)",
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm_io_gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "sys.SysSystem": {
            "type": "object",
            "required": [
                "AppId",
                "AppSecret"
            ],
            "properties": {
                "AppId": {
                    "description": "AppId",
                    "type": "string"
                },
                "AppSecret": {
                    "description": "AppSecret",
                    "type": "string"
                },
                "IP": {
                    "description": "系统来源IP",
                    "type": "string"
                },
                "Operator": {
                    "description": "操作人",
                    "type": "string"
                },
                "SystemName": {
                    "description": "系统名称",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm_io_gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "go-gin-rest-api",
	Description:      "go-gin-rest-api Golang后台api开发脚手架",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
